apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  mongodb-uri: "mongodb://yourUsername:yourPassword@yourMongoServiceName:yourPort/yourDatabase?authSource=yourDatabase"